version: "3.5"

services:
  odn-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: forex-admin
    image: odn-frontend
    entrypoint: yarn start:testing
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - rnd-ecommerce

networks:
  rnd-ecommerce:
    external:
      name: rnd-ecommerce